### ISSUE TITLE
Summary shouldn't reiterate app name

### ISSUE THREAD

**Issue by razzeee** [flathub/net.imaginaryinfinity.Squiid#1]
Hey,

we usually recommend to not reiterate the app name in the summary https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/#dont-repeat-the-name

**Comment by TabulateJarl8** [comment]
Sorry that I didn't see this sooner, I had notifications off for this repository. This was fixed in https://gitlab.com/ImaginaryInfinity/squiid-calculator/squiid/-/issues/53
